req:
  url: "https://api.first.org/data/v1/countries"

https:
  host: "0.0.0.0"
  port: "8082"
  path: "/api/*"
  timeout: "30000"
  jkspath: "sdfc.jks"
  password: "![E/uk21EyAACSASEU29q5Gg==]"
  alias: "mule"
  